"""
M5 Forecast API

Serves pre-computed forecasts from data/predictions/m5_forecast.parquet.
Predictions are generated by the m5_training_pipeline or m5_batch_inference DAGs.

Endpoints:
  GET  /health          – liveness check
  GET  /items           – list available unique_ids
  GET  /models          – list available forecast columns
  POST /predict         – return forecasts for a given unique_id
  POST /refresh         – reload the forecast parquet from disk
"""

from __future__ import annotations

import os
import json
import datetime
from contextlib import asynccontextmanager
from typing import Optional

import pandas as pd
import uvicorn
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

PREDICTIONS_PATH = "/opt/airflow/data/predictions/m5_forecast.parquet"
METRICS_PATH     = "/opt/airflow/models/model_metrics.json"
OUTPUT_PATH      = "/opt/airflow/outputs"

# Shared in-memory state
_state: dict = {"forecasts": pd.DataFrame()}


# ── Lifespan (replaces deprecated @app.on_event) ───────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load forecast data on startup."""
    _load_forecasts()
    yield


def _load_forecasts() -> None:
    """Read the latest forecast parquet into memory."""
    if os.path.exists(PREDICTIONS_PATH):
        df = pd.read_parquet(PREDICTIONS_PATH)
        df["ds"] = pd.to_datetime(df["ds"])
        _state["forecasts"] = df
        series_count = df["unique_id"].nunique()
        model_cols   = [c for c in df.columns if c not in ["unique_id", "ds"]]
        print(
            f"✅ Forecasts loaded: {len(df):,} rows, "
            f"{series_count:,} series, models={model_cols}"
        )
    else:
        _state["forecasts"] = pd.DataFrame()
        print(
            "⚠  Forecast file not found at "
            f"{PREDICTIONS_PATH}. Run the training pipeline first."
        )


# ── App ────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="M5 Forecast API",
    description="Serves M5 demand forecasts generated by StatsForecast & LightGBM",
    version="2.0",
    lifespan=lifespan,
)


# ── Schemas ────────────────────────────────────────────────────────────────

class PredictRequest(BaseModel):
    unique_id: str = Field(..., example="HOBBIES_1_001_CA_1_validation")
    horizon:   int = Field(28, ge=1, le=365, description="Steps ahead to return")
    model:     Optional[str] = Field(
        None,
        description="Specific model column to return (e.g. 'AutoETS'). "
                    "Omit to return all models.",
    )


class PredictResponse(BaseModel):
    status:    str
    unique_id: str
    rows:      int
    models:    list[str]
    saved_to:  str


# ── Helpers ────────────────────────────────────────────────────────────────

def _get_forecasts() -> pd.DataFrame:
    df = _state["forecasts"]
    if df.empty:
        raise HTTPException(
            status_code=503,
            detail="Forecast data not loaded. Run the training/inference pipeline first.",
        )
    return df


def _log_predictions(df: pd.DataFrame) -> str:
    """Append predictions to the output log parquet."""
    os.makedirs(OUTPUT_PATH, exist_ok=True)
    log_path = os.path.join(OUTPUT_PATH, "predictions_log.parquet")
    if os.path.exists(log_path):
        existing = pd.read_parquet(log_path)
        df = pd.concat([existing, df], ignore_index=True)
    df.to_parquet(log_path, index=False)
    return log_path


# ── Endpoints ──────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    forecasts = _state["forecasts"]
    return {
        "status":  "ok",
        "series":  int(forecasts["unique_id"].nunique()) if not forecasts.empty else 0,
        "rows":    len(forecasts),
        "models":  [c for c in forecasts.columns if c not in ["unique_id", "ds"]]
                   if not forecasts.empty else [],
    }


@app.get("/items")
def list_items(limit: int = 200):
    """Return up to `limit` unique_ids available in the forecast data."""
    df = _get_forecasts()
    items = df["unique_id"].unique().tolist()
    return {"count": len(items), "items": items[:limit]}


@app.get("/models")
def list_models():
    """Return available forecast model columns and stored metrics."""
    df = _get_forecasts()
    model_cols = [c for c in df.columns if c not in ["unique_id", "ds"]]
    metrics = []
    if os.path.exists(METRICS_PATH):
        metrics = json.loads(open(METRICS_PATH).read())
    return {"models": model_cols, "metrics": metrics}


@app.post("/predict", response_model=PredictResponse)
def predict(req: PredictRequest):
    """Return h-step forecasts for a single series."""
    df = _get_forecasts()

    mask = df["unique_id"] == req.unique_id
    item_df = df[mask].sort_values("ds").head(req.horizon).copy()

    if item_df.empty:
        available = df["unique_id"].unique()[:5].tolist()
        raise HTTPException(
            status_code=404,
            detail=f"No forecasts found for '{req.unique_id}'. "
                   f"Sample available IDs: {available}",
        )

    model_cols = [c for c in item_df.columns if c not in ["unique_id", "ds"]]

    # Filter to requested model if specified
    if req.model:
        if req.model not in model_cols:
            raise HTTPException(
                status_code=400,
                detail=f"Model '{req.model}' not found. Available: {model_cols}",
            )
        model_cols = [req.model]

    output_df  = item_df[["unique_id", "ds"] + model_cols].copy()
    log_path   = _log_predictions(output_df)

    return PredictResponse(
        status="ok",
        unique_id=req.unique_id,
        rows=len(output_df),
        models=model_cols,
        saved_to=log_path,
    )


@app.post("/refresh")
def refresh():
    """Reload forecast parquet from disk (call after training completes)."""
    _load_forecasts()
    df = _state["forecasts"]
    return {
        "status": "refreshed",
        "rows":   len(df),
        "series": int(df["unique_id"].nunique()) if not df.empty else 0,
    }


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
